<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>graph_BarChart</name>
   <tag></tag>
   <elementGuidId>6c90431a-bb4b-4089-97e4-fdfb62da67f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='dashboardCanvas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dashboardCanvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>c3a24ac3-d127-4ca7-9db5-5987ec3bf9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f1987e49-befe-4d41-a808-2790f0b74cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dashboardCanvas</value>
      <webElementGuid>8f290a1a-40e9-449a-9c1a-6942d59456de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>0980864e-27b1-4efb-b11b-dc314078a062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>bf5cd5cc-3e61-4727-83d5-564eeea4fcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboardCanvas&quot;)</value>
      <webElementGuid>bbd6377b-e71f-474c-a067-24e0d68d153e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='dashboardCanvas']</value>
      <webElementGuid>f7405845-4caa-4a4e-814b-d68ae5d5ee44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='graphical-dashboard']/div/div/div/canvas</value>
      <webElementGuid>8ae3b967-442b-4e52-aaec-86325b834b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>85713981-d13f-4de4-9b73-c8f98334954d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'dashboardCanvas']</value>
      <webElementGuid>2145834d-4265-4d27-85a0-2782e555d6e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
