<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_DayWithMostExpenses</name>
   <tag></tag>
   <elementGuidId>6c21ba97-d711-465a-be71-edbd1fcbc518</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='graphical-dashboard']/div/div/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f7fe9888-f6ef-4b18-b369-3a11eb237e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Most spent on: 12, November 2023</value>
      <webElementGuid>f087224b-a6bf-4473-956e-4daa45cdc824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;graphical-dashboard&quot;)/div[1]/div[@class=&quot;barchart-container&quot;]/div[1]/p[2]</value>
      <webElementGuid>1776a507-8c79-4b09-b1aa-aa9182d0c8ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='graphical-dashboard']/div/div/div/p[2]</value>
      <webElementGuid>b32959a6-6dd6-408f-8020-fad1f9c27e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='November Expenses'])[1]/following::p[2]</value>
      <webElementGuid>797b090c-8e36-44c3-a0d8-1518734f9277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Dashboard'])[1]/preceding::p[1]</value>
      <webElementGuid>eaf1a7b6-70ed-4960-81c3-350b0231db72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::p[1]</value>
      <webElementGuid>76a07ceb-25a8-4691-bef7-6567aac5859f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Most spent on: 12, November 2023']/parent::*</value>
      <webElementGuid>69137525-5fc6-4d85-977e-8bcda21a4412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>85439d19-9b4f-4406-af87-51eb724b6515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Most spent on: 12, November 2023' or . = 'Most spent on: 12, November 2023')]</value>
      <webElementGuid>ff9c44a2-ad40-492b-b8b5-9fe45ef8723d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
