version: '2'

services:
  frontend:
    image: 'chanakya10/expense-management-frontend'
    build:
      context: ./Front-end
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

  backend:
    image: 'chanakya10/expense-management-backend'
    build:
      context: ./Backend
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "9111:9111"
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root