
# Stage 2: Maven Build
FROM maven:3.8.4-openjdk-11 AS build

# Set the working directory
WORKDIR /app

# Copy the source code into the container
COPY src /app/src
COPY pom.xml /app

# Download dependencies
RUN mvn dependency:go-offline

# Compile the Java file
RUN mvn clean package -DskipTests

# Stage 3: Final Image with JRE
FROM openjdk:11-jre-slim

# Set the working directory
WORKDIR /app

# Copy the compiled JAR file from the build stage
COPY --from=build /app/target /app

# Expose the port that the Spring Boot app will run on
EXPOSE 9111

# CMD to run the Spring Boot application
CMD ["java", "-jar", "expense-manager-backend.jar"]
