<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_GraphicalDashboard</name>
   <tag></tag>
   <elementGuidId>0013adfe-6c78-45af-b77a-1c110570ea60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/a[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(3) > button.action-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7b6679ed-48a5-4528-b563-8f66c5d2278a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action-btn</value>
      <webElementGuid>2e84d2bf-ad88-48a5-9520-92a9358e97de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Graphical Dashboard</value>
      <webElementGuid>2e8f9c7b-82a1-4a56-b78f-6fb811c991bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;dashboard-container&quot;]/div[@class=&quot;main-content&quot;]/a[3]/button[@class=&quot;action-btn&quot;]</value>
      <webElementGuid>b3b2afcb-749b-4d94-9e8d-315c8f661b5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/a[3]/button</value>
      <webElementGuid>e6bbadbb-ccb1-4ecd-b767-78b41fc2d843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expense Log'])[1]/following::button[1]</value>
      <webElementGuid>18b007e8-a9bf-49e1-82da-3fd897b38516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Expense'])[1]/following::button[2]</value>
      <webElementGuid>988ff983-5732-4d45-97d5-2a79ec98b0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>d16e557c-1917-49cd-a1c6-eeae2fae8305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[1]</value>
      <webElementGuid>c29b9819-00b1-4fe7-b00e-1f3dd75fcd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Graphical Dashboard']/parent::*</value>
      <webElementGuid>a8a15689-4552-4b5c-a2b8-8e869bfa9b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/button</value>
      <webElementGuid>4cee4fee-f0bd-4360-a8ef-5aa44c28cd03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Graphical Dashboard' or . = 'Graphical Dashboard')]</value>
      <webElementGuid>86bf06b3-e1a6-420d-89e5-c97fb7799017</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
