version: 2.1

jobs:
  setup-and-test:
    machine:
      image: ubuntu-2204:2022.07.1

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: Front-end/expense-management-frontend
      - run:
          name: Run Tests
          command: npm test
          working_directory: Front-end/expense-management-frontend

workflows:
  Setup_and_Test:
    jobs:
      - setup-and-test
