# version: 2.1

# jobs:
#   hello-job:
#     machine:
#       image: windows-default
#     steps:
#       - checkout # check out the code in the project directory
#       - run: echo "hello world" # run the `echo` command

# workflows:
#   my-workflow:
#     jobs:
#       - hello-job
version: 2.1

jobs:
  hello-job:
    machine:
      image: windows-default

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: Write-Host 'Hello, Windows'

workflows:
  my-workflow:
    jobs:
      - hello-job
