version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_and_push:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: 
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME_1/dockerfile-python:${CIRCLE_SHA1} .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_PASS_1" | docker login --username $DOCKERHUB_USERNAME_1 --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $DOCKERHUB_USERNAME_1/myapp:${CIRCLE_SHA1}

  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push:
        filters:
          branches:
          only: EMS-50
