version: 2.1

jobs:
  test-and-deploy:
    machine:
      image: ubuntu-2204:2022.07.1

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: Front-end/expense-management-frontend
      - run:
          name: Run Tests
          command: npm test
          working_directory: Front-end/expense-management-frontend

      - run:
          name: Build Docker Image
          command: |
            docker build -t "$DOCKERHUB_USERNAME"/expense-management-system:latest .

      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push "$DOCKERHUB_USERNAME"/expense-management-system:latest

workflows:
  Test_and_Deploy:
    jobs:
      - test-and-deploy
