version: 2.1

jobs:
  setup-test:
    machine:
      image: ubuntu-2204:2022.07.1

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: ../Front-end/expense-management-frontend  # Set the working directory to the correct path
      - run:
          name: Run Tests
          command: npm test
          working_directory: ../Front-end/expense-management-frontend  # Set the working directory to the correct path

workflows:
  Setup_Test:
    jobs:
      - setup-test
