# version: 2.1

# jobs:
#   hello-job:
#     machine:
#       image: ubuntu-2204:2022.07.1

#     steps:
#       # Commands are run in a Windows virtual machine environment
#       - checkout
#       - run: echo "Hello, World!"

# workflows:
#   my-workflow:
#     jobs:
#       - hello-job


version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@23.0.11
workflows:
  build:
    jobs:
      - katalon-studio/run:
          version: latest
          command_arguments: >-
            -browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='..\Automation\ExpenseManagementAutomation\Test/ Suites\Example\ExampleTestSuite'
         
