version: 2.1

jobs:
  setup-test:
    machine:
      image: windows-latest:2022-07-10

    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  Setup_Test:
    jobs:
      - setup-test