version: 2.1

jobs:
  setup-and-test:
    machine:
      image: ubuntu-2204:2022.07.1

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: Front-end/expense-management-frontend
      - run:
          name: Run Tests
          command: npm test
          working_directory: Front-end/expense-management-frontend

      - run:
          name: Build Docker Image
          command: |
            docker build -t "$DOCKERHUB_USERNAME"/expense-management-system:"${CIRCLE_SHA1}" .

      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push "$DOCKERHUB_USERNAME"/expense-management-system:"${CIRCLE_SHA1}"

workflows:
  Setup_and_Test:
    jobs:
      - setup-and-test
