version: 2.1

jobs:
  setup-test:
    machine:
      image: ubuntu-2204:2022.07.1

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: Front-end/expense-management-frontend
      - run:
          name: Run Tests
          command: npm test
          working_directory: Front-end/expense-management-frontend
      
      - persist_to_workspace:
          root: Front-end/expense-management-frontend
          paths:
            - test-reports

workflows:
  Setup_Test:
    jobs:
      - setup-test
