version: 2.1

jobs:
  setup-test:
    machine:
      image: ubuntu-2204:2022.07.1

    steps:
      - checkout
      - run:
          name: List Working Directory Contents
          command: ls -al
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: Front-end/expense-management-frontend
      - run:
          name: Run Tests
          command: npm test
          working_directory: ~/project/ExpenseManagementSystem/Front-end/expense-management-frontend

workflows:
  Setup_Test:
    jobs:
      - setup-test
