version: 2.1

jobs:
  setup-test:
    machine:
      image: ubuntu-2204:2022.07.1

    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  Setup_Test:
    jobs:
      - setup-test
