version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:2022.07.1

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: Front-end/expense-management-frontend
      - run:
          name: Run Tests
          command: npm test
          working_directory: Front-end/expense-management-frontend

  build-and-push:
    docker:
      - image: docker:20.10.9
    steps:
      - checkout
      - run:
          name: Build frontend Docker Image
          working_directory: Front-end
          command: |
            docker build -t "$DOCKERHUB_USERNAME"/expense-management-frontend:latest .
      - run:
          name: Build backend Docker Image
          working_directory: Backend
          command: |
            docker build -t "$DOCKERHUB_USERNAME"/expense-management-backend:latest .
      - run:
          name: Push Images to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push "$DOCKERHUB_USERNAME"/expense-management-frontend:latest
            docker push "$DOCKERHUB_USERNAME"/expense-management-backend:latest

workflows:
  version: 2
  Test_and_Deploy:
    jobs:
      - test
      
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only:
                - main
