version: 2.1

jobs:
  setup-dependancies:
    machine:
      image: windows-latest:2022-07-10

    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  my-workflow:
    jobs:
      - setup-dependancies